# Generated by Django 6.0 on 2025-12-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('duration', models.IntegerField()),
                ('course_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
